//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperOfficeWinApp.Service.SoWcfAssociate
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoCredentials", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfAssociate.SoSafeCredentials))]
    public partial class SoCredentials : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TicketField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticket
        {
            get
            {
                return this.TicketField;
            }
            set
            {
                this.TicketField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoSafeCredentials", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SoSafeCredentials : SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoTimeZone", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SoTimeZone : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SoTimeZoneIdField;
        
        private string SoTimeZoneLocationCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoTimeZoneId
        {
            get
            {
                return this.SoTimeZoneIdField;
            }
            set
            {
                this.SoTimeZoneIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoTimeZoneLocationCode
        {
            get
            {
                return this.SoTimeZoneLocationCodeField;
            }
            set
            {
                this.SoTimeZoneLocationCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoExceptionInfo", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SoExceptionInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ExceptionTypeField;
        
        private string FriendlyTextField;
        
        private SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo InnerExceptionField;
        
        private string MessageField;
        
        private SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfoParameters ParametersField;
        
        private string SourceField;
        
        private string StackTraceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType
        {
            get
            {
                return this.ExceptionTypeField;
            }
            set
            {
                this.ExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyText
        {
            get
            {
                return this.FriendlyTextField;
            }
            set
            {
                this.FriendlyTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo InnerException
        {
            get
            {
                return this.InnerExceptionField;
            }
            set
            {
                this.InnerExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfoParameters Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SoExceptionInfoParameters", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", ItemName="SoExceptionInfoParametersKeyValuePair", KeyName="ParameterKey", ValueName="ParameterValue")]
    public class SoExceptionInfoParameters : System.Collections.Generic.Dictionary<string, string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carrier", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfAssociate.Associate))]
    public partial class Carrier : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SuperOfficeWinApp.Service.SoWcfAssociate.FieldPropertyDictionary FieldPropertiesField;
        
        private SuperOfficeWinApp.Service.SoWcfAssociate.TableRight TableRightField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfAssociate.FieldPropertyDictionary FieldProperties
        {
            get
            {
                return this.FieldPropertiesField;
            }
            set
            {
                this.FieldPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfAssociate.TableRight TableRight
        {
            get
            {
                return this.TableRightField;
            }
            set
            {
                this.TableRightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class TableRight : SuperOfficeWinApp.Service.SoWcfAssociate.GenericRight
    {
        
        private SuperOfficeWinApp.Service.SoWcfAssociate.ETableRight MaskField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfAssociate.ETableRight Mask
        {
            get
            {
                return this.MaskField;
            }
            set
            {
                this.MaskField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Associate", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class Associate : SuperOfficeWinApp.Service.SoWcfAssociate.Carrier
    {
        
        private int AssociateIdField;
        
        private bool DeletedField;
        
        private int EjUserIdField;
        
        private string FormalNameField;
        
        private string FullNameField;
        
        private int GroupIdxField;
        
        private string NameField;
        
        private int PersonIdField;
        
        private short RankField;
        
        private string TooltipField;
        
        private SuperOfficeWinApp.Service.SoWcfAssociate.UserType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssociateId
        {
            get
            {
                return this.AssociateIdField;
            }
            set
            {
                this.AssociateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EjUserId
        {
            get
            {
                return this.EjUserIdField;
            }
            set
            {
                this.EjUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormalName
        {
            get
            {
                return this.FormalNameField;
            }
            set
            {
                this.FormalNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupIdx
        {
            get
            {
                return this.GroupIdxField;
            }
            set
            {
                this.GroupIdxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Rank
        {
            get
            {
                return this.RankField;
            }
            set
            {
                this.RankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tooltip
        {
            get
            {
                return this.TooltipField;
            }
            set
            {
                this.TooltipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfAssociate.UserType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FieldPropertyDictionary", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", ItemName="FieldPropertyDictionaryKeyValuePair", KeyName="Key", ValueName="FieldProperty")]
    public class FieldPropertyDictionary : System.Collections.Generic.Dictionary<string, SuperOfficeWinApp.Service.SoWcfAssociate.FieldProperty>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://license.superoffice.com/1.0")]
    public enum UserType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalAssociate = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceAssociate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalAssociate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnonymousAssociate = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemAssociate = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldProperty", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class FieldProperty : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FieldLengthField;
        
        private SuperOfficeWinApp.Service.SoWcfAssociate.FieldRight FieldRightField;
        
        private string FieldTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FieldLength
        {
            get
            {
                return this.FieldLengthField;
            }
            set
            {
                this.FieldLengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfAssociate.FieldRight FieldRight
        {
            get
            {
                return this.FieldRightField;
            }
            set
            {
                this.FieldRightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldType
        {
            get
            {
                return this.FieldTypeField;
            }
            set
            {
                this.FieldTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class FieldRight : SuperOfficeWinApp.Service.SoWcfAssociate.ItemRight
    {
        
        private SuperOfficeWinApp.Service.SoWcfAssociate.EFieldRight MaskField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfAssociate.EFieldRight Mask
        {
            get
            {
                return this.MaskField;
            }
            set
            {
                this.MaskField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfAssociate.TableRight))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfAssociate.ItemRight))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfAssociate.FieldRight))]
    public partial class GenericRight : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemRight", Namespace="http://schemas.datacontract.org/2004/07/SuperOffice.CRM.Security")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfAssociate.FieldRight))]
    public partial class ItemRight : SuperOfficeWinApp.Service.SoWcfAssociate.GenericRight
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="EFieldRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public enum EFieldRight : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Write = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused1 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused2 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused3 = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused4 = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UIHintMandatory = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UIHintReadOnly = 128,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETableRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public enum ETableRight : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Select = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Filtering = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RestrictedUpdate = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused1 = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uninitialized = 128,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Associate", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", ConfigurationName="SuperOfficeWinApp.Service.SoWcfAssociate.Associate1")]
    public interface Associate1
    {
        
        // CODEGEN: Generating message contract since message GetAssociateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/GetAssociate", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/GetAssociateR" +
            "esponse")]
        SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateResponse GetAssociate(SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateRequest request);
        
        // CODEGEN: Generating message contract since message GetAssociateByPersonIdRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/GetAssociateB" +
            "yPersonId", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/GetAssociateB" +
            "yPersonIdResponse")]
        SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateByPersonIdResponse GetAssociateByPersonId(SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateByPersonIdRequest request);
        
        // CODEGEN: Generating message contract since message GetNoteRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/GetNote", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/GetNoteRespon" +
            "se")]
        SuperOfficeWinApp.Service.SoWcfAssociate.GetNoteResponse GetNote(SuperOfficeWinApp.Service.SoWcfAssociate.GetNoteRequest request);
        
        // CODEGEN: Generating message contract since message SaveNoteRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/SaveNote", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/SaveNoteRespo" +
            "nse")]
        SuperOfficeWinApp.Service.SoWcfAssociate.SaveNoteResponse SaveNote(SuperOfficeWinApp.Service.SoWcfAssociate.SaveNoteRequest request);
        
        // CODEGEN: Generating message contract since message GetAssociateListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/GetAssociateL" +
            "ist", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/GetAssociateL" +
            "istResponse")]
        SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateListResponse GetAssociateList(SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateListRequest request);
        
        // CODEGEN: Generating message contract since message GetAssociatesByGroupRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/GetAssociates" +
            "ByGroup", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/Associate/GetAssociates" +
            "ByGroupResponse")]
        SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociatesByGroupResponse GetAssociatesByGroup(SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociatesByGroupRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociate", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetAssociateRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public int AssociateId;
        
        public GetAssociateRequest()
        {
        }
        
        public GetAssociateRequest(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int AssociateId)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AssociateId = AssociateId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociateResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetAssociateResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfAssociate.Associate Response;
        
        public GetAssociateResponse()
        {
        }
        
        public GetAssociateResponse(SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfAssociate.Associate Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociateByPersonId", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetAssociateByPersonIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public int PersonId;
        
        public GetAssociateByPersonIdRequest()
        {
        }
        
        public GetAssociateByPersonIdRequest(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int PersonId)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.PersonId = PersonId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociateByPersonIdResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetAssociateByPersonIdResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfAssociate.Associate Response;
        
        public GetAssociateByPersonIdResponse()
        {
        }
        
        public GetAssociateByPersonIdResponse(SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfAssociate.Associate Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNote", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetNoteRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public int AssociateId;
        
        public GetNoteRequest()
        {
        }
        
        public GetNoteRequest(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int AssociateId)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AssociateId = AssociateId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNoteResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetNoteResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public string[] Response;
        
        public GetNoteResponse()
        {
        }
        
        public GetNoteResponse(SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, string[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveNote", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class SaveNoteRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public int AssociateId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=1)]
        public string[] Note;
        
        public SaveNoteRequest()
        {
        }
        
        public SaveNoteRequest(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int AssociateId, string[] Note)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AssociateId = AssociateId;
            this.Note = Note;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveNoteResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class SaveNoteResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        public SaveNoteResponse()
        {
        }
        
        public SaveNoteResponse(SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociateList", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetAssociateListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public int[] AssociateIds;
        
        public GetAssociateListRequest()
        {
        }
        
        public GetAssociateListRequest(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int[] AssociateIds)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AssociateIds = AssociateIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociateListResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetAssociateListResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfAssociate.Associate[] Response;
        
        public GetAssociateListResponse()
        {
        }
        
        public GetAssociateListResponse(SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfAssociate.Associate[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociatesByGroup", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetAssociatesByGroupRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public int GroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=1)]
        public int Type;
        
        public GetAssociatesByGroupRequest()
        {
        }
        
        public GetAssociatesByGroupRequest(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int GroupId, int Type)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.GroupId = GroupId;
            this.Type = Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssociatesByGroupResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetAssociatesByGroupResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfAssociate.Associate[] Response;
        
        public GetAssociatesByGroupResponse()
        {
        }
        
        public GetAssociatesByGroupResponse(SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfAssociate.Associate[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Associate1Channel : SuperOfficeWinApp.Service.SoWcfAssociate.Associate1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Associate1Client : System.ServiceModel.ClientBase<SuperOfficeWinApp.Service.SoWcfAssociate.Associate1>, SuperOfficeWinApp.Service.SoWcfAssociate.Associate1
    {
        
        public Associate1Client()
        {
        }
        
        public Associate1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public Associate1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Associate1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Associate1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateResponse SuperOfficeWinApp.Service.SoWcfAssociate.Associate1.GetAssociate(SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateRequest request)
        {
            return base.Channel.GetAssociate(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo GetAssociate(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int AssociateId, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfAssociate.Associate Response)
        {
            SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateRequest inValue = new SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateId = AssociateId;
            SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateResponse retVal = ((SuperOfficeWinApp.Service.SoWcfAssociate.Associate1)(this)).GetAssociate(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateByPersonIdResponse SuperOfficeWinApp.Service.SoWcfAssociate.Associate1.GetAssociateByPersonId(SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateByPersonIdRequest request)
        {
            return base.Channel.GetAssociateByPersonId(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo GetAssociateByPersonId(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int PersonId, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfAssociate.Associate Response)
        {
            SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateByPersonIdRequest inValue = new SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateByPersonIdRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.PersonId = PersonId;
            SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateByPersonIdResponse retVal = ((SuperOfficeWinApp.Service.SoWcfAssociate.Associate1)(this)).GetAssociateByPersonId(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfAssociate.GetNoteResponse SuperOfficeWinApp.Service.SoWcfAssociate.Associate1.GetNote(SuperOfficeWinApp.Service.SoWcfAssociate.GetNoteRequest request)
        {
            return base.Channel.GetNote(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo GetNote(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int AssociateId, out bool Succeeded, out string[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfAssociate.GetNoteRequest inValue = new SuperOfficeWinApp.Service.SoWcfAssociate.GetNoteRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateId = AssociateId;
            SuperOfficeWinApp.Service.SoWcfAssociate.GetNoteResponse retVal = ((SuperOfficeWinApp.Service.SoWcfAssociate.Associate1)(this)).GetNote(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfAssociate.SaveNoteResponse SuperOfficeWinApp.Service.SoWcfAssociate.Associate1.SaveNote(SuperOfficeWinApp.Service.SoWcfAssociate.SaveNoteRequest request)
        {
            return base.Channel.SaveNote(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo SaveNote(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int AssociateId, string[] Note, out bool Succeeded)
        {
            SuperOfficeWinApp.Service.SoWcfAssociate.SaveNoteRequest inValue = new SuperOfficeWinApp.Service.SoWcfAssociate.SaveNoteRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateId = AssociateId;
            inValue.Note = Note;
            SuperOfficeWinApp.Service.SoWcfAssociate.SaveNoteResponse retVal = ((SuperOfficeWinApp.Service.SoWcfAssociate.Associate1)(this)).SaveNote(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateListResponse SuperOfficeWinApp.Service.SoWcfAssociate.Associate1.GetAssociateList(SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateListRequest request)
        {
            return base.Channel.GetAssociateList(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo GetAssociateList(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int[] AssociateIds, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfAssociate.Associate[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateListRequest inValue = new SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateListRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AssociateIds = AssociateIds;
            SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociateListResponse retVal = ((SuperOfficeWinApp.Service.SoWcfAssociate.Associate1)(this)).GetAssociateList(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociatesByGroupResponse SuperOfficeWinApp.Service.SoWcfAssociate.Associate1.GetAssociatesByGroup(SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociatesByGroupRequest request)
        {
            return base.Channel.GetAssociatesByGroup(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfAssociate.SoExceptionInfo GetAssociatesByGroup(SuperOfficeWinApp.Service.SoWcfAssociate.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfAssociate.SoTimeZone TimeZone, int GroupId, int Type, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfAssociate.Associate[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociatesByGroupRequest inValue = new SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociatesByGroupRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.GroupId = GroupId;
            inValue.Type = Type;
            SuperOfficeWinApp.Service.SoWcfAssociate.GetAssociatesByGroupResponse retVal = ((SuperOfficeWinApp.Service.SoWcfAssociate.Associate1)(this)).GetAssociatesByGroup(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
    }
}
