//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperOfficeWinApp.Service.SoWcfMdo
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoCredentials", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfMdo.SoSafeCredentials))]
    public partial class SoCredentials : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TicketField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticket
        {
            get
            {
                return this.TicketField;
            }
            set
            {
                this.TicketField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoSafeCredentials", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SoSafeCredentials : SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoTimeZone", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SoTimeZone : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SoTimeZoneIdField;
        
        private string SoTimeZoneLocationCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoTimeZoneId
        {
            get
            {
                return this.SoTimeZoneIdField;
            }
            set
            {
                this.SoTimeZoneIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoTimeZoneLocationCode
        {
            get
            {
                return this.SoTimeZoneLocationCodeField;
            }
            set
            {
                this.SoTimeZoneLocationCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoExceptionInfo", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SoExceptionInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ExceptionTypeField;
        
        private string FriendlyTextField;
        
        private SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo InnerExceptionField;
        
        private string MessageField;
        
        private SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfoParameters ParametersField;
        
        private string SourceField;
        
        private string StackTraceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType
        {
            get
            {
                return this.ExceptionTypeField;
            }
            set
            {
                this.ExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyText
        {
            get
            {
                return this.FriendlyTextField;
            }
            set
            {
                this.FriendlyTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo InnerException
        {
            get
            {
                return this.InnerExceptionField;
            }
            set
            {
                this.InnerExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfoParameters Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SoExceptionInfoParameters", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", ItemName="SoExceptionInfoParametersKeyValuePair", KeyName="ParameterKey", ValueName="ParameterValue")]
    public class SoExceptionInfoParameters : System.Collections.Generic.Dictionary<string, string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDOListItem", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class MDOListItem : SuperOfficeWinApp.Service.SoWcfMdo.Carrier
    {
        
        private SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] ChildItemsField;
        
        private int ColorBlockField;
        
        private bool DeletedField;
        
        private string ExtraInfoField;
        
        private string IconHintField;
        
        private int IdField;
        
        private string NameField;
        
        private int RankField;
        
        private string StyleHintField;
        
        private string ToolTipField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] ChildItems
        {
            get
            {
                return this.ChildItemsField;
            }
            set
            {
                this.ChildItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ColorBlock
        {
            get
            {
                return this.ColorBlockField;
            }
            set
            {
                this.ColorBlockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraInfo
        {
            get
            {
                return this.ExtraInfoField;
            }
            set
            {
                this.ExtraInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconHint
        {
            get
            {
                return this.IconHintField;
            }
            set
            {
                this.IconHintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rank
        {
            get
            {
                return this.RankField;
            }
            set
            {
                this.RankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleHint
        {
            get
            {
                return this.StyleHintField;
            }
            set
            {
                this.StyleHintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolTip
        {
            get
            {
                return this.ToolTipField;
            }
            set
            {
                this.ToolTipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carrier", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem))]
    public partial class Carrier : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SuperOfficeWinApp.Service.SoWcfMdo.FieldPropertyDictionary FieldPropertiesField;
        
        private SuperOfficeWinApp.Service.SoWcfMdo.TableRight TableRightField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfMdo.FieldPropertyDictionary FieldProperties
        {
            get
            {
                return this.FieldPropertiesField;
            }
            set
            {
                this.FieldPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfMdo.TableRight TableRight
        {
            get
            {
                return this.TableRightField;
            }
            set
            {
                this.TableRightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class TableRight : SuperOfficeWinApp.Service.SoWcfMdo.GenericRight
    {
        
        private SuperOfficeWinApp.Service.SoWcfMdo.ETableRight MaskField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfMdo.ETableRight Mask
        {
            get
            {
                return this.MaskField;
            }
            set
            {
                this.MaskField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectableMDOListItem", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SelectableMDOListItem : SuperOfficeWinApp.Service.SoWcfMdo.Carrier
    {
        
        private SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] ChildItemsField;
        
        private int ColorBlockField;
        
        private bool DeletedField;
        
        private string ExtraInfoField;
        
        private bool HiddenField;
        
        private string IconHintField;
        
        private int IdField;
        
        private System.DateTime LastChangedField;
        
        private string NameField;
        
        private int RankField;
        
        private bool SelectedField;
        
        private string StyleHintField;
        
        private string ToolTipField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] ChildItems
        {
            get
            {
                return this.ChildItemsField;
            }
            set
            {
                this.ChildItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ColorBlock
        {
            get
            {
                return this.ColorBlockField;
            }
            set
            {
                this.ColorBlockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraInfo
        {
            get
            {
                return this.ExtraInfoField;
            }
            set
            {
                this.ExtraInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Hidden
        {
            get
            {
                return this.HiddenField;
            }
            set
            {
                this.HiddenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconHint
        {
            get
            {
                return this.IconHintField;
            }
            set
            {
                this.IconHintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChanged
        {
            get
            {
                return this.LastChangedField;
            }
            set
            {
                this.LastChangedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rank
        {
            get
            {
                return this.RankField;
            }
            set
            {
                this.RankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Selected
        {
            get
            {
                return this.SelectedField;
            }
            set
            {
                this.SelectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleHint
        {
            get
            {
                return this.StyleHintField;
            }
            set
            {
                this.StyleHintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolTip
        {
            get
            {
                return this.ToolTipField;
            }
            set
            {
                this.ToolTipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FieldPropertyDictionary", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", ItemName="FieldPropertyDictionaryKeyValuePair", KeyName="Key", ValueName="FieldProperty")]
    public class FieldPropertyDictionary : System.Collections.Generic.Dictionary<string, SuperOfficeWinApp.Service.SoWcfMdo.FieldProperty>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldProperty", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class FieldProperty : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FieldLengthField;
        
        private SuperOfficeWinApp.Service.SoWcfMdo.FieldRight FieldRightField;
        
        private string FieldTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FieldLength
        {
            get
            {
                return this.FieldLengthField;
            }
            set
            {
                this.FieldLengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfMdo.FieldRight FieldRight
        {
            get
            {
                return this.FieldRightField;
            }
            set
            {
                this.FieldRightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldType
        {
            get
            {
                return this.FieldTypeField;
            }
            set
            {
                this.FieldTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class FieldRight : SuperOfficeWinApp.Service.SoWcfMdo.ItemRight
    {
        
        private SuperOfficeWinApp.Service.SoWcfMdo.EFieldRight MaskField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfMdo.EFieldRight Mask
        {
            get
            {
                return this.MaskField;
            }
            set
            {
                this.MaskField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfMdo.TableRight))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfMdo.ItemRight))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfMdo.FieldRight))]
    public partial class GenericRight : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemRight", Namespace="http://schemas.datacontract.org/2004/07/SuperOffice.CRM.Security")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfMdo.FieldRight))]
    public partial class ItemRight : SuperOfficeWinApp.Service.SoWcfMdo.GenericRight
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="EFieldRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public enum EFieldRight : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Write = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused1 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused2 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused3 = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused4 = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UIHintMandatory = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UIHintReadOnly = 128,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETableRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public enum ETableRight : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Select = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Filtering = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RestrictedUpdate = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused1 = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uninitialized = 128,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", ConfigurationName="SuperOfficeWinApp.Service.SoWcfMdo.MDO")]
    public interface MDO
    {
        
        // CODEGEN: Generating message contract since message GetListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetList", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetListResponse")]
        SuperOfficeWinApp.Service.SoWcfMdo.GetListResponse GetList(SuperOfficeWinApp.Service.SoWcfMdo.GetListRequest request);
        
        // CODEGEN: Generating message contract since message GetListWithHistoryRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetListWithHistory", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetListWithHistoryR" +
            "esponse")]
        SuperOfficeWinApp.Service.SoWcfMdo.GetListWithHistoryResponse GetListWithHistory(SuperOfficeWinApp.Service.SoWcfMdo.GetListWithHistoryRequest request);
        
        // CODEGEN: Generating message contract since message GetListWithRestrictionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetListWithRestrict" +
            "ion", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetListWithRestrict" +
            "ionResponse")]
        SuperOfficeWinApp.Service.SoWcfMdo.GetListWithRestrictionResponse GetListWithRestriction(SuperOfficeWinApp.Service.SoWcfMdo.GetListWithRestrictionRequest request);
        
        // CODEGEN: Generating message contract since message GetSimpleListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetSimpleList", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetSimpleListRespon" +
            "se")]
        SuperOfficeWinApp.Service.SoWcfMdo.GetSimpleListResponse GetSimpleList(SuperOfficeWinApp.Service.SoWcfMdo.GetSimpleListRequest request);
        
        // CODEGEN: Generating message contract since message GetSelectableSimpleListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetSelectableSimple" +
            "List", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetSelectableSimple" +
            "ListResponse")]
        SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableSimpleListResponse GetSelectableSimpleList(SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableSimpleListRequest request);
        
        // CODEGEN: Generating message contract since message GetSelectableListWithRestrictionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetSelectableListWi" +
            "thRestriction", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetSelectableListWi" +
            "thRestrictionResponse")]
        SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithRestrictionResponse GetSelectableListWithRestriction(SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithRestrictionRequest request);
        
        // CODEGEN: Generating message contract since message GetSelectableListWithHistoryRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetSelectableListWi" +
            "thHistory", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetSelectableListWi" +
            "thHistoryResponse")]
        SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithHistoryResponse GetSelectableListWithHistory(SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithHistoryRequest request);
        
        // CODEGEN: Generating message contract since message GetSelectableListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetSelectableList", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/GetSelectableListRe" +
            "sponse")]
        SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListResponse GetSelectableList(SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListRequest request);
        
        // CODEGEN: Generating message contract since message SetSelectedRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/SetSelected", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/MDO/SetSelectedResponse" +
            "")]
        SuperOfficeWinApp.Service.SoWcfMdo.SetSelectedResponse SetSelected(SuperOfficeWinApp.Service.SoWcfMdo.SetSelectedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetList", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public string AdditionalInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=1)]
        public bool ForceFlatList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=2)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=3)]
        public bool OnlyHistory;
        
        public GetListRequest()
        {
        }
        
        public GetListRequest(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, bool ForceFlatList, string Name, bool OnlyHistory)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AdditionalInfo = AdditionalInfo;
            this.ForceFlatList = ForceFlatList;
            this.Name = Name;
            this.OnlyHistory = OnlyHistory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetListResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response;
        
        public GetListResponse()
        {
        }
        
        public GetListResponse(SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListWithHistory", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetListWithHistoryRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public string AdditionalInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=1)]
        public bool ForceFlatList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=2)]
        public int[] HistoryItems;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=3)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=4)]
        public bool OnlyHistory;
        
        public GetListWithHistoryRequest()
        {
        }
        
        public GetListWithHistoryRequest(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, bool ForceFlatList, int[] HistoryItems, string Name, bool OnlyHistory)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AdditionalInfo = AdditionalInfo;
            this.ForceFlatList = ForceFlatList;
            this.HistoryItems = HistoryItems;
            this.Name = Name;
            this.OnlyHistory = OnlyHistory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListWithHistoryResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetListWithHistoryResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response;
        
        public GetListWithHistoryResponse()
        {
        }
        
        public GetListWithHistoryResponse(SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListWithRestriction", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetListWithRestrictionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public string AdditionalInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=1)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=2)]
        public string SearchValue;
        
        public GetListWithRestrictionRequest()
        {
        }
        
        public GetListWithRestrictionRequest(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, string Name, string SearchValue)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AdditionalInfo = AdditionalInfo;
            this.Name = Name;
            this.SearchValue = SearchValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListWithRestrictionResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetListWithRestrictionResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response;
        
        public GetListWithRestrictionResponse()
        {
        }
        
        public GetListWithRestrictionResponse(SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSimpleList", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetSimpleListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public string Name;
        
        public GetSimpleListRequest()
        {
        }
        
        public GetSimpleListRequest(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string Name)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSimpleListResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetSimpleListResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response;
        
        public GetSimpleListResponse()
        {
        }
        
        public GetSimpleListResponse(SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSelectableSimpleList", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetSelectableSimpleListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public string Name;
        
        public GetSelectableSimpleListRequest()
        {
        }
        
        public GetSelectableSimpleListRequest(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string Name)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSelectableSimpleListResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetSelectableSimpleListResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response;
        
        public GetSelectableSimpleListResponse()
        {
        }
        
        public GetSelectableSimpleListResponse(SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSelectableListWithRestriction", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetSelectableListWithRestrictionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public string AdditionalInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=1)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=2)]
        public string SearchValue;
        
        public GetSelectableListWithRestrictionRequest()
        {
        }
        
        public GetSelectableListWithRestrictionRequest(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, string Name, string SearchValue)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AdditionalInfo = AdditionalInfo;
            this.Name = Name;
            this.SearchValue = SearchValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSelectableListWithRestrictionResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetSelectableListWithRestrictionResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response;
        
        public GetSelectableListWithRestrictionResponse()
        {
        }
        
        public GetSelectableListWithRestrictionResponse(SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSelectableListWithHistory", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetSelectableListWithHistoryRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public string AdditionalInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=1)]
        public bool ForceFlatList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=2)]
        public int[] HistoryItems;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=3)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=4)]
        public bool OnlyHistory;
        
        public GetSelectableListWithHistoryRequest()
        {
        }
        
        public GetSelectableListWithHistoryRequest(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, bool ForceFlatList, int[] HistoryItems, string Name, bool OnlyHistory)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AdditionalInfo = AdditionalInfo;
            this.ForceFlatList = ForceFlatList;
            this.HistoryItems = HistoryItems;
            this.Name = Name;
            this.OnlyHistory = OnlyHistory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSelectableListWithHistoryResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetSelectableListWithHistoryResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response;
        
        public GetSelectableListWithHistoryResponse()
        {
        }
        
        public GetSelectableListWithHistoryResponse(SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSelectableList", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetSelectableListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public string AdditionalInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=1)]
        public bool ForceFlatList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=2)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=3)]
        public bool OnlyHistory;
        
        public GetSelectableListRequest()
        {
        }
        
        public GetSelectableListRequest(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, bool ForceFlatList, string Name, bool OnlyHistory)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AdditionalInfo = AdditionalInfo;
            this.ForceFlatList = ForceFlatList;
            this.Name = Name;
            this.OnlyHistory = OnlyHistory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSelectableListResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetSelectableListResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response;
        
        public GetSelectableListResponse()
        {
        }
        
        public GetSelectableListResponse(SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetSelected", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class SetSelectedRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public string AdditionalInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=1)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=2)]
        public SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] SelectableMDOList;
        
        public SetSelectedRequest()
        {
        }
        
        public SetSelectedRequest(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, string Name, SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] SelectableMDOList)
        {
            this.Credentials = Credentials;
            this.TimeZone = TimeZone;
            this.AdditionalInfo = AdditionalInfo;
            this.Name = Name;
            this.SelectableMDOList = SelectableMDOList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetSelectedResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class SetSelectedResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response;
        
        public SetSelectedResponse()
        {
        }
        
        public SetSelectedResponse(SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface MDOChannel : SuperOfficeWinApp.Service.SoWcfMdo.MDO, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MDOClient : System.ServiceModel.ClientBase<SuperOfficeWinApp.Service.SoWcfMdo.MDO>, SuperOfficeWinApp.Service.SoWcfMdo.MDO
    {
        
        public MDOClient()
        {
        }
        
        public MDOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MDOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MDOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MDOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfMdo.GetListResponse SuperOfficeWinApp.Service.SoWcfMdo.MDO.GetList(SuperOfficeWinApp.Service.SoWcfMdo.GetListRequest request)
        {
            return base.Channel.GetList(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo GetList(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, bool ForceFlatList, string Name, bool OnlyHistory, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfMdo.GetListRequest inValue = new SuperOfficeWinApp.Service.SoWcfMdo.GetListRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AdditionalInfo = AdditionalInfo;
            inValue.ForceFlatList = ForceFlatList;
            inValue.Name = Name;
            inValue.OnlyHistory = OnlyHistory;
            SuperOfficeWinApp.Service.SoWcfMdo.GetListResponse retVal = ((SuperOfficeWinApp.Service.SoWcfMdo.MDO)(this)).GetList(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfMdo.GetListWithHistoryResponse SuperOfficeWinApp.Service.SoWcfMdo.MDO.GetListWithHistory(SuperOfficeWinApp.Service.SoWcfMdo.GetListWithHistoryRequest request)
        {
            return base.Channel.GetListWithHistory(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo GetListWithHistory(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, bool ForceFlatList, int[] HistoryItems, string Name, bool OnlyHistory, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfMdo.GetListWithHistoryRequest inValue = new SuperOfficeWinApp.Service.SoWcfMdo.GetListWithHistoryRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AdditionalInfo = AdditionalInfo;
            inValue.ForceFlatList = ForceFlatList;
            inValue.HistoryItems = HistoryItems;
            inValue.Name = Name;
            inValue.OnlyHistory = OnlyHistory;
            SuperOfficeWinApp.Service.SoWcfMdo.GetListWithHistoryResponse retVal = ((SuperOfficeWinApp.Service.SoWcfMdo.MDO)(this)).GetListWithHistory(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfMdo.GetListWithRestrictionResponse SuperOfficeWinApp.Service.SoWcfMdo.MDO.GetListWithRestriction(SuperOfficeWinApp.Service.SoWcfMdo.GetListWithRestrictionRequest request)
        {
            return base.Channel.GetListWithRestriction(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo GetListWithRestriction(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, string Name, string SearchValue, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfMdo.GetListWithRestrictionRequest inValue = new SuperOfficeWinApp.Service.SoWcfMdo.GetListWithRestrictionRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AdditionalInfo = AdditionalInfo;
            inValue.Name = Name;
            inValue.SearchValue = SearchValue;
            SuperOfficeWinApp.Service.SoWcfMdo.GetListWithRestrictionResponse retVal = ((SuperOfficeWinApp.Service.SoWcfMdo.MDO)(this)).GetListWithRestriction(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfMdo.GetSimpleListResponse SuperOfficeWinApp.Service.SoWcfMdo.MDO.GetSimpleList(SuperOfficeWinApp.Service.SoWcfMdo.GetSimpleListRequest request)
        {
            return base.Channel.GetSimpleList(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo GetSimpleList(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string Name, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfMdo.MDOListItem[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfMdo.GetSimpleListRequest inValue = new SuperOfficeWinApp.Service.SoWcfMdo.GetSimpleListRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.Name = Name;
            SuperOfficeWinApp.Service.SoWcfMdo.GetSimpleListResponse retVal = ((SuperOfficeWinApp.Service.SoWcfMdo.MDO)(this)).GetSimpleList(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableSimpleListResponse SuperOfficeWinApp.Service.SoWcfMdo.MDO.GetSelectableSimpleList(SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableSimpleListRequest request)
        {
            return base.Channel.GetSelectableSimpleList(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo GetSelectableSimpleList(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string Name, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableSimpleListRequest inValue = new SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableSimpleListRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.Name = Name;
            SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableSimpleListResponse retVal = ((SuperOfficeWinApp.Service.SoWcfMdo.MDO)(this)).GetSelectableSimpleList(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithRestrictionResponse SuperOfficeWinApp.Service.SoWcfMdo.MDO.GetSelectableListWithRestriction(SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithRestrictionRequest request)
        {
            return base.Channel.GetSelectableListWithRestriction(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo GetSelectableListWithRestriction(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, string Name, string SearchValue, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithRestrictionRequest inValue = new SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithRestrictionRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AdditionalInfo = AdditionalInfo;
            inValue.Name = Name;
            inValue.SearchValue = SearchValue;
            SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithRestrictionResponse retVal = ((SuperOfficeWinApp.Service.SoWcfMdo.MDO)(this)).GetSelectableListWithRestriction(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithHistoryResponse SuperOfficeWinApp.Service.SoWcfMdo.MDO.GetSelectableListWithHistory(SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithHistoryRequest request)
        {
            return base.Channel.GetSelectableListWithHistory(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo GetSelectableListWithHistory(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, bool ForceFlatList, int[] HistoryItems, string Name, bool OnlyHistory, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithHistoryRequest inValue = new SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithHistoryRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AdditionalInfo = AdditionalInfo;
            inValue.ForceFlatList = ForceFlatList;
            inValue.HistoryItems = HistoryItems;
            inValue.Name = Name;
            inValue.OnlyHistory = OnlyHistory;
            SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListWithHistoryResponse retVal = ((SuperOfficeWinApp.Service.SoWcfMdo.MDO)(this)).GetSelectableListWithHistory(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListResponse SuperOfficeWinApp.Service.SoWcfMdo.MDO.GetSelectableList(SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListRequest request)
        {
            return base.Channel.GetSelectableList(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo GetSelectableList(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, bool ForceFlatList, string Name, bool OnlyHistory, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListRequest inValue = new SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AdditionalInfo = AdditionalInfo;
            inValue.ForceFlatList = ForceFlatList;
            inValue.Name = Name;
            inValue.OnlyHistory = OnlyHistory;
            SuperOfficeWinApp.Service.SoWcfMdo.GetSelectableListResponse retVal = ((SuperOfficeWinApp.Service.SoWcfMdo.MDO)(this)).GetSelectableList(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfMdo.SetSelectedResponse SuperOfficeWinApp.Service.SoWcfMdo.MDO.SetSelected(SuperOfficeWinApp.Service.SoWcfMdo.SetSelectedRequest request)
        {
            return base.Channel.SetSelected(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfMdo.SoExceptionInfo SetSelected(SuperOfficeWinApp.Service.SoWcfMdo.SoCredentials Credentials, ref SuperOfficeWinApp.Service.SoWcfMdo.SoTimeZone TimeZone, string AdditionalInfo, string Name, SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] SelectableMDOList, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfMdo.SelectableMDOListItem[] Response)
        {
            SuperOfficeWinApp.Service.SoWcfMdo.SetSelectedRequest inValue = new SuperOfficeWinApp.Service.SoWcfMdo.SetSelectedRequest();
            inValue.Credentials = Credentials;
            inValue.TimeZone = TimeZone;
            inValue.AdditionalInfo = AdditionalInfo;
            inValue.Name = Name;
            inValue.SelectableMDOList = SelectableMDOList;
            SuperOfficeWinApp.Service.SoWcfMdo.SetSelectedResponse retVal = ((SuperOfficeWinApp.Service.SoWcfMdo.MDO)(this)).SetSelected(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            return retVal.ExceptionInfo;
        }
    }
}
