//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperOfficeWinApp.Service.SoWcfSoPrincipal
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoExceptionInfo", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SoExceptionInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ExceptionTypeField;
        
        private string FriendlyTextField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfo InnerExceptionField;
        
        private string MessageField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfoParameters ParametersField;
        
        private string SourceField;
        
        private string StackTraceField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType
        {
            get
            {
                return this.ExceptionTypeField;
            }
            set
            {
                this.ExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyText
        {
            get
            {
                return this.FriendlyTextField;
            }
            set
            {
                this.FriendlyTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfo InnerException
        {
            get
            {
                return this.InnerExceptionField;
            }
            set
            {
                this.InnerExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfoParameters Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SoExceptionInfoParameters", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", ItemName="SoExceptionInfoParametersKeyValuePair", KeyName="ParameterKey", ValueName="ParameterValue")]
    public class SoExceptionInfoParameters : System.Collections.Generic.Dictionary<string, string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoTimeZone", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SoTimeZone : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SoTimeZoneIdField;
        
        private string SoTimeZoneLocationCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoTimeZoneId
        {
            get
            {
                return this.SoTimeZoneIdField;
            }
            set
            {
                this.SoTimeZoneIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoTimeZoneLocationCode
        {
            get
            {
                return this.SoTimeZoneLocationCodeField;
            }
            set
            {
                this.SoTimeZoneLocationCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carrier", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfSoPrincipal.GrantedModuleLicense))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoSystemInfoCarrier))]
    public partial class Carrier : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.FieldPropertyDictionary FieldPropertiesField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.TableRight TableRightField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.FieldPropertyDictionary FieldProperties
        {
            get
            {
                return this.FieldPropertiesField;
            }
            set
            {
                this.FieldPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.TableRight TableRight
        {
            get
            {
                return this.TableRightField;
            }
            set
            {
                this.TableRightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class TableRight : SuperOfficeWinApp.Service.SoWcfSoPrincipal.GenericRight
    {
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.ETableRight MaskField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.ETableRight Mask
        {
            get
            {
                return this.MaskField;
            }
            set
            {
                this.MaskField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrantedModuleLicense", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class GrantedModuleLicense : SuperOfficeWinApp.Service.SoWcfSoPrincipal.Carrier
    {
        
        private string DescriptionField;
        
        private System.DateTime ExpiryDateField;
        
        private int ExtraFlagsField;
        
        private string ExtraInfoField;
        
        private bool IsHiddenField;
        
        private bool IsUnrestrictedField;
        
        private int LicenseNumberField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.LicenseType LicenseTypeField;
        
        private int ModuleIdField;
        
        private string NameField;
        
        private string OwnerDescriptionField;
        
        private int OwnerIdField;
        
        private string OwnerNameField;
        
        private int SortOrderField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtraFlags
        {
            get
            {
                return this.ExtraFlagsField;
            }
            set
            {
                this.ExtraFlagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraInfo
        {
            get
            {
                return this.ExtraInfoField;
            }
            set
            {
                this.ExtraInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHidden
        {
            get
            {
                return this.IsHiddenField;
            }
            set
            {
                this.IsHiddenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUnrestricted
        {
            get
            {
                return this.IsUnrestrictedField;
            }
            set
            {
                this.IsUnrestrictedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LicenseNumber
        {
            get
            {
                return this.LicenseNumberField;
            }
            set
            {
                this.LicenseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.LicenseType LicenseType
        {
            get
            {
                return this.LicenseTypeField;
            }
            set
            {
                this.LicenseTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModuleId
        {
            get
            {
                return this.ModuleIdField;
            }
            set
            {
                this.ModuleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerDescription
        {
            get
            {
                return this.OwnerDescriptionField;
            }
            set
            {
                this.OwnerDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName
        {
            get
            {
                return this.OwnerNameField;
            }
            set
            {
                this.OwnerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoSystemInfoCarrier", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SoSystemInfoCarrier : SuperOfficeWinApp.Service.SoWcfSoPrincipal.Carrier
    {
        
        private System.DateTime AccumulatedNextCheckDateField;
        
        private string AssemblyVersionField;
        
        private string BranchNameField;
        
        private string BuildLabelField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.NetServerBuildType BuildTypeField;
        
        private string CompanyNameField;
        
        private string DatabaseTypeField;
        
        private int DatabaseVersionField;
        
        private int DaysUntilNetServerExpiryField;
        
        private string DescriptionField;
        
        private string FileVersionField;
        
        private bool IsUnicodeField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.LicenseInfo LicenseField;
        
        private string WarningEnglishField;
        
        private string WarningResourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AccumulatedNextCheckDate
        {
            get
            {
                return this.AccumulatedNextCheckDateField;
            }
            set
            {
                this.AccumulatedNextCheckDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssemblyVersion
        {
            get
            {
                return this.AssemblyVersionField;
            }
            set
            {
                this.AssemblyVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildLabel
        {
            get
            {
                return this.BuildLabelField;
            }
            set
            {
                this.BuildLabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.NetServerBuildType BuildType
        {
            get
            {
                return this.BuildTypeField;
            }
            set
            {
                this.BuildTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatabaseType
        {
            get
            {
                return this.DatabaseTypeField;
            }
            set
            {
                this.DatabaseTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DatabaseVersion
        {
            get
            {
                return this.DatabaseVersionField;
            }
            set
            {
                this.DatabaseVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DaysUntilNetServerExpiry
        {
            get
            {
                return this.DaysUntilNetServerExpiryField;
            }
            set
            {
                this.DaysUntilNetServerExpiryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileVersion
        {
            get
            {
                return this.FileVersionField;
            }
            set
            {
                this.FileVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUnicode
        {
            get
            {
                return this.IsUnicodeField;
            }
            set
            {
                this.IsUnicodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.LicenseInfo License
        {
            get
            {
                return this.LicenseField;
            }
            set
            {
                this.LicenseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarningEnglish
        {
            get
            {
                return this.WarningEnglishField;
            }
            set
            {
                this.WarningEnglishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarningResource
        {
            get
            {
                return this.WarningResourceField;
            }
            set
            {
                this.WarningResourceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FieldPropertyDictionary", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", ItemName="FieldPropertyDictionaryKeyValuePair", KeyName="Key", ValueName="FieldProperty")]
    public class FieldPropertyDictionary : System.Collections.Generic.Dictionary<string, SuperOfficeWinApp.Service.SoWcfSoPrincipal.FieldProperty>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LicenseInfo", Namespace="http://license.superoffice.com/1.0")]
    public partial class LicenseInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime AdminWarningDateField;
        
        private string CompanyNameField;
        
        private int DeploymentTypeField;
        
        private System.DateTime ExpiryDateField;
        
        private int ExtraFlagsField;
        
        private string ExtraInfoField;
        
        private System.DateTime GraceDateField;
        
        private string LicenseUrlField;
        
        private string LicenseVersionField;
        
        private System.DateTime MaintenanceDateField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.ModuleLicense[] ModuleLicensesField;
        
        private System.DateTime NextCheckDateField;
        
        private string OwnerDescriptionField;
        
        private string OwnerNameField;
        
        private string ProductDescriptionField;
        
        private string ProductTypeField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.SignedPublicKey PublicKeyField;
        
        private string SerialNrField;
        
        private string SignatureField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AdminWarningDate
        {
            get
            {
                return this.AdminWarningDateField;
            }
            set
            {
                this.AdminWarningDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeploymentType
        {
            get
            {
                return this.DeploymentTypeField;
            }
            set
            {
                this.DeploymentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtraFlags
        {
            get
            {
                return this.ExtraFlagsField;
            }
            set
            {
                this.ExtraFlagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraInfo
        {
            get
            {
                return this.ExtraInfoField;
            }
            set
            {
                this.ExtraInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime GraceDate
        {
            get
            {
                return this.GraceDateField;
            }
            set
            {
                this.GraceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseUrl
        {
            get
            {
                return this.LicenseUrlField;
            }
            set
            {
                this.LicenseUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseVersion
        {
            get
            {
                return this.LicenseVersionField;
            }
            set
            {
                this.LicenseVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MaintenanceDate
        {
            get
            {
                return this.MaintenanceDateField;
            }
            set
            {
                this.MaintenanceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.ModuleLicense[] ModuleLicenses
        {
            get
            {
                return this.ModuleLicensesField;
            }
            set
            {
                this.ModuleLicensesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NextCheckDate
        {
            get
            {
                return this.NextCheckDateField;
            }
            set
            {
                this.NextCheckDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerDescription
        {
            get
            {
                return this.OwnerDescriptionField;
            }
            set
            {
                this.OwnerDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName
        {
            get
            {
                return this.OwnerNameField;
            }
            set
            {
                this.OwnerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDescription
        {
            get
            {
                return this.ProductDescriptionField;
            }
            set
            {
                this.ProductDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductType
        {
            get
            {
                return this.ProductTypeField;
            }
            set
            {
                this.ProductTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SignedPublicKey PublicKey
        {
            get
            {
                return this.PublicKeyField;
            }
            set
            {
                this.PublicKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNr
        {
            get
            {
                return this.SerialNrField;
            }
            set
            {
                this.SerialNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NetServerBuildType", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public enum NetServerBuildType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Feature = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stable = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alpha = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Beta = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReleaseCandidate = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Release = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldProperty", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class FieldProperty : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FieldLengthField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.FieldRight FieldRightField;
        
        private string FieldTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FieldLength
        {
            get
            {
                return this.FieldLengthField;
            }
            set
            {
                this.FieldLengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.FieldRight FieldRight
        {
            get
            {
                return this.FieldRightField;
            }
            set
            {
                this.FieldRightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldType
        {
            get
            {
                return this.FieldTypeField;
            }
            set
            {
                this.FieldTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LicenseType", Namespace="http://license.superoffice.com/1.0")]
    public enum LicenseType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SiteLicense = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SatelliteLicense = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserLicense = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class FieldRight : SuperOfficeWinApp.Service.SoWcfSoPrincipal.ItemRight
    {
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.EFieldRight MaskField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.EFieldRight Mask
        {
            get
            {
                return this.MaskField;
            }
            set
            {
                this.MaskField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfSoPrincipal.TableRight))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfSoPrincipal.ItemRight))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfSoPrincipal.FieldRight))]
    public partial class GenericRight : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemRight", Namespace="http://schemas.datacontract.org/2004/07/SuperOffice.CRM.Security")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfSoPrincipal.FieldRight))]
    public partial class ItemRight : SuperOfficeWinApp.Service.SoWcfSoPrincipal.GenericRight
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="EFieldRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public enum EFieldRight : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Write = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused1 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused2 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused3 = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused4 = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UIHintMandatory = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UIHintReadOnly = 128,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETableRight", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public enum ETableRight : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Select = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Filtering = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RestrictedUpdate = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unused1 = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uninitialized = 128,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignedPublicKey", Namespace="http://license.superoffice.com/1.0")]
    public partial class SignedPublicKey : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ExpiryDateField;
        
        private System.Security.Cryptography.DSAParameters KeyField;
        
        private string OwnerNameField;
        
        private System.DateTime SignDateField;
        
        private string SignatureField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiryDate
        {
            get
            {
                return this.ExpiryDateField;
            }
            set
            {
                this.ExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Security.Cryptography.DSAParameters Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName
        {
            get
            {
                return this.OwnerNameField;
            }
            set
            {
                this.OwnerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SignDate
        {
            get
            {
                return this.SignDateField;
            }
            set
            {
                this.SignDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModuleLicense", Namespace="http://license.superoffice.com/1.0")]
    public partial class ModuleLicense : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.UserType AllowedUserTypeField;
        
        private int ExtraFlagsField;
        
        private string ExtraInfoField;
        
        private bool IsHiddenField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.LicenseType LicenseTypeField;
        
        private string ModuleDescriptionField;
        
        private string ModuleNameField;
        
        private string ModuleTooltipField;
        
        private string ModuleVersionField;
        
        private int NumberOfLicensesField;
        
        private string OwnerNameField;
        
        private string PrerequisiteModuleNameField;
        
        private string SignatureField;
        
        private int SortOrderField;
        
        private bool UnrestrictedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.UserType AllowedUserType
        {
            get
            {
                return this.AllowedUserTypeField;
            }
            set
            {
                this.AllowedUserTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtraFlags
        {
            get
            {
                return this.ExtraFlagsField;
            }
            set
            {
                this.ExtraFlagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraInfo
        {
            get
            {
                return this.ExtraInfoField;
            }
            set
            {
                this.ExtraInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHidden
        {
            get
            {
                return this.IsHiddenField;
            }
            set
            {
                this.IsHiddenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.LicenseType LicenseType
        {
            get
            {
                return this.LicenseTypeField;
            }
            set
            {
                this.LicenseTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleDescription
        {
            get
            {
                return this.ModuleDescriptionField;
            }
            set
            {
                this.ModuleDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName
        {
            get
            {
                return this.ModuleNameField;
            }
            set
            {
                this.ModuleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleTooltip
        {
            get
            {
                return this.ModuleTooltipField;
            }
            set
            {
                this.ModuleTooltipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleVersion
        {
            get
            {
                return this.ModuleVersionField;
            }
            set
            {
                this.ModuleVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfLicenses
        {
            get
            {
                return this.NumberOfLicensesField;
            }
            set
            {
                this.NumberOfLicensesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName
        {
            get
            {
                return this.OwnerNameField;
            }
            set
            {
                this.OwnerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrerequisiteModuleName
        {
            get
            {
                return this.PrerequisiteModuleNameField;
            }
            set
            {
                this.PrerequisiteModuleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Unrestricted
        {
            get
            {
                return this.UnrestrictedField;
            }
            set
            {
                this.UnrestrictedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://license.superoffice.com/1.0")]
    public enum UserType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalAssociate = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResourceAssociate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalAssociate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnonymousAssociate = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemAssociate = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoPrincipalCarrier", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SoPrincipalCarrier : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AssociateField;
        
        private int AssociateIdField;
        
        private int BusinessIdField;
        
        private string CRM5SecretField;
        
        private int CategoryIdField;
        
        private int ContactIdField;
        
        private int ContactOwnerField;
        
        private int CountryIdField;
        
        private string EMailAddressField;
        
        private int EjAccessLevelField;
        
        private int EjUserIdField;
        
        private string FullNameField;
        
        private string[] FunctionRightsField;
        
        private int GroupIdField;
        
        private int HomeCountryIdField;
        
        private bool IsPersonField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.ProductLicense LicenseField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.GrantedModuleLicense[] LicensesField;
        
        private int PersonIdField;
        
        private string RoleDescriptionField;
        
        private int RoleIdField;
        
        private string RoleNameField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.RoleType RoleTypeField;
        
        private SuperOfficeWinApp.Service.SoWcfSoPrincipal.UserType UserTypeField;
        
        private int[] SecondaryGroupsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Associate
        {
            get
            {
                return this.AssociateField;
            }
            set
            {
                this.AssociateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssociateId
        {
            get
            {
                return this.AssociateIdField;
            }
            set
            {
                this.AssociateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusinessId
        {
            get
            {
                return this.BusinessIdField;
            }
            set
            {
                this.BusinessIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRM5Secret
        {
            get
            {
                return this.CRM5SecretField;
            }
            set
            {
                this.CRM5SecretField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactId
        {
            get
            {
                return this.ContactIdField;
            }
            set
            {
                this.ContactIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactOwner
        {
            get
            {
                return this.ContactOwnerField;
            }
            set
            {
                this.ContactOwnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                this.CountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMailAddress
        {
            get
            {
                return this.EMailAddressField;
            }
            set
            {
                this.EMailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EjAccessLevel
        {
            get
            {
                return this.EjAccessLevelField;
            }
            set
            {
                this.EjAccessLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EjUserId
        {
            get
            {
                return this.EjUserIdField;
            }
            set
            {
                this.EjUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] FunctionRights
        {
            get
            {
                return this.FunctionRightsField;
            }
            set
            {
                this.FunctionRightsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId
        {
            get
            {
                return this.GroupIdField;
            }
            set
            {
                this.GroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HomeCountryId
        {
            get
            {
                return this.HomeCountryIdField;
            }
            set
            {
                this.HomeCountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPerson
        {
            get
            {
                return this.IsPersonField;
            }
            set
            {
                this.IsPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.ProductLicense License
        {
            get
            {
                return this.LicenseField;
            }
            set
            {
                this.LicenseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.GrantedModuleLicense[] Licenses
        {
            get
            {
                return this.LicensesField;
            }
            set
            {
                this.LicensesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleDescription
        {
            get
            {
                return this.RoleDescriptionField;
            }
            set
            {
                this.RoleDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.RoleType RoleType
        {
            get
            {
                return this.RoleTypeField;
            }
            set
            {
                this.RoleTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.UserType UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public int[] SecondaryGroups
        {
            get
            {
                return this.SecondaryGroupsField;
            }
            set
            {
                this.SecondaryGroupsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductLicense", Namespace="http://schemas.datacontract.org/2004/07/SuperOffice.License")]
    public enum ProductLicense : uint
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 4294967295,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Site = 4294901760,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 65535,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deprecatable = 4278251520,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Login = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WinLogin = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebLogin = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Publish = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreateExternalPerson = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfidentialAppointment = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReporterStudio = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Travel = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoteTravel = 512,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SyncEngine = 1024,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PocketLogin = 2048,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Win = 65536,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Web = 131072,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Audience = 262144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExpanderKey = 16777216,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExpanderForCollaboration = 33554432,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebServices = 67108864,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Saint = 134217728,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pocket = 268435456,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductTypeCRMSoftware = 536870912,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductTypeOnlineStd = 1073741824,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductTypeOnlinePro = 2147483648,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleType", Namespace="http://schemas.datacontract.org/2004/07/SuperOffice.CRM.Services")]
    public enum RoleType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Employee = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalUser = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Anonymous = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoCredentials", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoSafeCredentials))]
    public partial class SoCredentials : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TicketField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticket
        {
            get
            {
                return this.TicketField;
            }
            set
            {
                this.TicketField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoSafeCredentials", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
    public partial class SoSafeCredentials : SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoCredentials
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AuthenticationGenericData", Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", ItemName="AuthenticationGenericDataKeyValuePair", KeyName="Key", ValueName="Value")]
    public class AuthenticationGenericData : System.Collections.Generic.Dictionary<string, string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", ConfigurationName="SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal")]
    public interface SoPrincipal
    {
        
        // CODEGEN: Generating message contract since the operation GetSystemInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/SoPrincipal/GetSystemIn" +
            "fo", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/SoPrincipal/GetSystemIn" +
            "foResponse")]
        SuperOfficeWinApp.Service.SoWcfSoPrincipal.GetSystemInfoResponse GetSystemInfo(SuperOfficeWinApp.Service.SoWcfSoPrincipal.GetSystemInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation AuthenticateImplicit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/SoPrincipal/Authenticat" +
            "eImplicit", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/SoPrincipal/Authenticat" +
            "eImplicitResponse")]
        SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateResponse AuthenticateImplicit(SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateImplicitRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (AuthenticateResponse) of message AuthenticateResponse does not match the default value (AuthenticateUsernamePassword)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/SoPrincipal/Authenticat" +
            "eUsernamePassword", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/SoPrincipal/Authenticat" +
            "eUsernamePasswordResponse")]
        SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateResponse AuthenticateUsernamePassword(SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateUsernamePasswordRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (AuthenticateResponse) of message AuthenticateResponse does not match the default value (AuthenticateGeneric)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/SoPrincipal/Authenticat" +
            "eGeneric", ReplyAction="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000/SoPrincipal/Authenticat" +
            "eGenericResponse")]
        SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateResponse AuthenticateGeneric(SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateGenericRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemInfoRequest
    {
        
        public GetSystemInfoRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSystemInfoResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class GetSystemInfoResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoSystemInfoCarrier SystemInfo;
        
        public GetSystemInfoResponse()
        {
        }
        
        public GetSystemInfoResponse(SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoSystemInfoCarrier SystemInfo)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.SystemInfo = SystemInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateImplicitRequest
    {
        
        public AuthenticateImplicitRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateResponse", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class AuthenticateResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfo ExceptionInfo;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public bool Succeeded;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000")]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoTimeZone TimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipalCarrier Response;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=1)]
        public bool AuthenticationSucceeded;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=2)]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoCredentials Credentials;
        
        public AuthenticateResponse()
        {
        }
        
        public AuthenticateResponse(SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfo ExceptionInfo, bool Succeeded, SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoTimeZone TimeZone, SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipalCarrier Response, bool AuthenticationSucceeded, SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoCredentials Credentials)
        {
            this.ExceptionInfo = ExceptionInfo;
            this.Succeeded = Succeeded;
            this.TimeZone = TimeZone;
            this.Response = Response;
            this.AuthenticationSucceeded = AuthenticationSucceeded;
            this.Credentials = Credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUsernamePassword", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class AuthenticateUsernamePasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=1)]
        public string UserName;
        
        public AuthenticateUsernamePasswordRequest()
        {
        }
        
        public AuthenticateUsernamePasswordRequest(string Password, string UserName)
        {
            this.Password = Password;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateGeneric", WrapperNamespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", IsWrapped=true)]
    public partial class AuthenticateGenericRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.superoffice.net/ws/crm/NetServer/7.0.2000.2000", Order=0)]
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticationGenericData AuthenticationData;
        
        public AuthenticateGenericRequest()
        {
        }
        
        public AuthenticateGenericRequest(SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticationGenericData AuthenticationData)
        {
            this.AuthenticationData = AuthenticationData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SoPrincipalChannel : SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SoPrincipalClient : System.ServiceModel.ClientBase<SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal>, SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal
    {
        
        public SoPrincipalClient()
        {
        }
        
        public SoPrincipalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SoPrincipalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SoPrincipalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SoPrincipalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfSoPrincipal.GetSystemInfoResponse SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal.GetSystemInfo(SuperOfficeWinApp.Service.SoWcfSoPrincipal.GetSystemInfoRequest request)
        {
            return base.Channel.GetSystemInfo(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfo GetSystemInfo(out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoTimeZone TimeZone, out SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoSystemInfoCarrier SystemInfo)
        {
            SuperOfficeWinApp.Service.SoWcfSoPrincipal.GetSystemInfoRequest inValue = new SuperOfficeWinApp.Service.SoWcfSoPrincipal.GetSystemInfoRequest();
            SuperOfficeWinApp.Service.SoWcfSoPrincipal.GetSystemInfoResponse retVal = ((SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal)(this)).GetSystemInfo(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            SystemInfo = retVal.SystemInfo;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateResponse SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal.AuthenticateImplicit(SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateImplicitRequest request)
        {
            return base.Channel.AuthenticateImplicit(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfo AuthenticateImplicit(out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoTimeZone TimeZone, out SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipalCarrier Response, out bool AuthenticationSucceeded, out SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoCredentials Credentials)
        {
            SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateImplicitRequest inValue = new SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateImplicitRequest();
            SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateResponse retVal = ((SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal)(this)).AuthenticateImplicit(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            AuthenticationSucceeded = retVal.AuthenticationSucceeded;
            Credentials = retVal.Credentials;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateResponse SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal.AuthenticateUsernamePassword(SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateUsernamePasswordRequest request)
        {
            return base.Channel.AuthenticateUsernamePassword(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfo AuthenticateUsernamePassword(string Password, string UserName, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoTimeZone TimeZone, out SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipalCarrier Response, out bool AuthenticationSucceeded, out SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoCredentials Credentials)
        {
            SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateUsernamePasswordRequest inValue = new SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateUsernamePasswordRequest();
            inValue.Password = Password;
            inValue.UserName = UserName;
            SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateResponse retVal = ((SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal)(this)).AuthenticateUsernamePassword(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            AuthenticationSucceeded = retVal.AuthenticationSucceeded;
            Credentials = retVal.Credentials;
            return retVal.ExceptionInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateResponse SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal.AuthenticateGeneric(SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateGenericRequest request)
        {
            return base.Channel.AuthenticateGeneric(request);
        }
        
        public SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoExceptionInfo AuthenticateGeneric(SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticationGenericData AuthenticationData, out bool Succeeded, out SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoTimeZone TimeZone, out SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipalCarrier Response, out bool AuthenticationSucceeded, out SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoCredentials Credentials)
        {
            SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateGenericRequest inValue = new SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateGenericRequest();
            inValue.AuthenticationData = AuthenticationData;
            SuperOfficeWinApp.Service.SoWcfSoPrincipal.AuthenticateResponse retVal = ((SuperOfficeWinApp.Service.SoWcfSoPrincipal.SoPrincipal)(this)).AuthenticateGeneric(inValue);
            Succeeded = retVal.Succeeded;
            TimeZone = retVal.TimeZone;
            Response = retVal.Response;
            AuthenticationSucceeded = retVal.AuthenticationSucceeded;
            Credentials = retVal.Credentials;
            return retVal.ExceptionInfo;
        }
    }
}
